apiVersion: skaffold/v1beta2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/villmond/tsoft-angular-demo:{{.VERSION}}"
  artifacts:
  - image: changeme
    context: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/villmond/tsoft-angular-demo:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: tsoft-angular-demo
        chartPath: charts/tsoft-angular-demo
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/villmond/tsoft-angular-demo"
          image.tag: "{{.DIGEST_HEX}}"
